version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mount
      - ls
      - ls efs
      - ./brew_install_efs.sh
      - echo Build done
  post_build:
    commands:
      - echo Build completed on `date`
